### ISSUE TITLE
Roadmap for the next deliverable

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/wiq_en2b#124]
# General changes
- [ ] #178
- [x] #140
- [x] #185
- [ ] #186
- [x] #187
- [x] #146
- [x] #133
- [x] #179
- [x] #132 
- [ ] #143
# Frontend changes
- [x] #125
- [x] #141
- [x] #158
- [x] #184
- [x] #139
- [x] #155
- [x] #157

## Fixes
- [x] Fix the bugs reported in #121 and #122.
- [x] #131
- [x] #134
- [x] #126

# Backend changes
- [X] Add more variety to questions (see #152).
- [x] #129
- [x] #196
- [ ] Add logged-in user data endpoint
- [x] #197
- [x] #130

**Comment by jjgancfer** [comment]
Closed due to the third delivery being over. See #214 for the new roadmap.
